apiVersion: apps/v1
kind: Deployment
metadata:
  name: springreview 
spec:
  selector:
    matchLabels:
      app: springreview
  template:
    metadata:
      labels:
        app: springreview
    spec:
      containers:
        - image: okteto.dev/java-gradle-springreview:1.0.0
          name: springreview

---

apiVersion: v1
kind: Service
metadata:
  name: springreview
spec:
  type: ClusterIP
  ports:
    - name: "springreview"
      port: 8080
  selector:
    app: springreview

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springreview
  annotations:
    dev.okteto.com/generate-host: springreview
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: springreview
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific